import Navigation from "../components/navigation"
import { Metadata } from "next";
import "../styles/global.css";

export const metadata = {
  title: {
    template: '%s | Next.js',
    default: 'Next Default'
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Navigation />
        {children}
      </body>
    </html>
  )
}
